card_as_unicode((2, hearts), '🂲').
card_as_unicode((3, hearts), '🂳').
card_as_unicode((4, hearts), '🂴').
card_as_unicode((5, hearts), '🂵').
card_as_unicode((6, hearts), '🂶').
card_as_unicode((7, hearts), '🂷').
card_as_unicode((8, hearts), '🂸').
card_as_unicode((9, hearts), '🂹').
card_as_unicode((10, hearts), '🂺').
card_as_unicode((jack, hearts), '🂻').
card_as_unicode((queen, hearts), '🂽').
card_as_unicode((king, hearts), '🂾').
card_as_unicode((ace, hearts), '🂱').

card_as_unicode((2, diamonds), '🃂').
card_as_unicode((3, diamonds), '🃃').
card_as_unicode((4, diamonds), '🃄').
card_as_unicode((5, diamonds), '🃅').
card_as_unicode((6, diamonds), '🃆').
card_as_unicode((7, diamonds), '🃇').
card_as_unicode((8, diamonds), '🃈').
card_as_unicode((9, diamonds), '🃉').
card_as_unicode((10, diamonds), '🃊').
card_as_unicode((jack, diamonds), '🃋').
card_as_unicode((queen, diamonds), '🃍').
card_as_unicode((king, diamonds), '🃎').
card_as_unicode((ace, diamonds), '🃁').

card_as_unicode((2, clubs), '🃒').
card_as_unicode((3, clubs), '🃓').
card_as_unicode((4, clubs), '🃔').
card_as_unicode((5, clubs), '🃕').
card_as_unicode((6, clubs), '🃖').
card_as_unicode((7, clubs), '🃗').
card_as_unicode((8, clubs), '🃘').
card_as_unicode((9, clubs), '🃙').
card_as_unicode((10, clubs), '🃚').
card_as_unicode((jack, clubs), '🃛').
card_as_unicode((queen, clubs), '🃝').
card_as_unicode((king, clubs), '🃞').
card_as_unicode((ace, clubs), '🃑').

card_as_unicode((2, spades), '🂢').
card_as_unicode((3, spades), '🂣').
card_as_unicode((4, spades), '🂤').
card_as_unicode((5, spades), '🂥').
card_as_unicode((6, spades), '🂦').
card_as_unicode((7, spades), '🂧').
card_as_unicode((8, spades), '🂨').
card_as_unicode((9, spades), '🂩').
card_as_unicode((10, spades), '🂪').
card_as_unicode((jack, spades), '🂫').
card_as_unicode((queen, spades), '🂭').
card_as_unicode((king, spades), '🂮').
card_as_unicode((ace, spades), '🂡').
